# Generated by Django 5.0.1 on 2024-01-21 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_score_app', '0005_modelscore_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscore',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
